Algoritmo "Média_3_notas"
// Descrição   : Calcular a média de 3 notas
// Autor(a)    : Diogo Remelgado
// Data atual  : 20/09/2017
Var
nota1, nota2, nota3, media:real


Inicio
escreva ("Qual a nota do primeiro aluno?")
Leia (nota1)
escreva ("Qual a nota do segundo aluno?")
Leia (nota2)
escreva ("Qual a nota do terceiro aluno?")
Leia (nota3)
media <- (nota1+nota2+nota3) / 3
escreva ("A média é", media)


Fimalgoritmo