Algoritmo "Volume_do_paralelepípedo"
// Descrição   : Calcular o Volume de um paralelepípedo
// Autor(a)    : Diogo Remelgado
// Data atual  : 20/09/2017
Var
base, altura, largura, volume:real


Inicio
Escreva ("Qual é a base?")
Leia (base)
Escreva ("Qual a altura?")
Leia (altura)
Escreva ("Qual a largura?")
Leia (largura)
volume <- base*altura*largura
Escreva (" O volume é", volume)


Fimalgoritmo