Algoritmo "Área_do_trapezio"
// Descrição   : Calcular a área de um trapezio
// Autor(a)    : Diogo Remelgado
// Data atual  : 20/09/2017
Var
baseMaior, baseMenor, altura, area: real


Inicio
Escreva ("Qual a base maior?")
Leia (baseMaior)
Escreva ("Qual a base menor?")
Leia (baseMenor)
Escreva ("Qual a altura?")
Leia (altura)
area <- (baseMaior + baseMenor)*altura / 2.0
escreva ("a área do trapezio é", area)
Fimalgoritmo